name: Hola Mundo

on: [push]


jobs:
  uno:
    runs-on: ubuntu-latest

    steps:
    - name: Mensaje
      run: echo "Hola mundo !!! " 
    - name: Touch File
      run: |
          touch hola.txt
          ls -al
    -  name: Set text
       run: |
            echo "Hola mundo" >> hola.txt
    -  name: Read File #Lee
       run: cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Directorio
      run: ls -al